/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminTabBar: typeof import('./src/components/layout/AdminTabBar.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    AppNavbarApp: typeof import('./src/components/layout/AppNavbarApp.vue')['default']
    AppNavbarVenue: typeof import('./src/components/layout/AppNavbarVenue.vue')['default']
    FloorPlanGrid: typeof import('./src/components/floor/FloorPlanGrid.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MenuCategoryHero: typeof import('./src/components/menu/MenuCategoryHero.vue')['default']
    MenuItemRow: typeof import('./src/components/menu/MenuItemRow.vue')['default']
    ReservationStatusChip: typeof import('./src/components/feedback/ReservationStatusChip.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SectionHeader: typeof import('./src/components/ui/SectionHeader.vue')['default']
    SpotlyDivider: typeof import('./src/components/ui/SpotlyDivider.vue')['default']
    SpotlySnackbar: typeof import('./src/components/feedback/SpotlySnackbar.vue')['default']
    StatCard: typeof import('./src/components/ui/StatCard.vue')['default']
    TableCard: typeof import('./src/components/floor/TableCard.vue')['default']
    TableDetailDialog: typeof import('./src/components/floor/TableDetailDialog.vue')['default']
  }
}
