/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/admin/floor-plan': RouteRecordInfo<'/admin/floor-plan', '/admin/floor-plan', Record<never, never>, Record<never, never>>,
    '/admin/menu': RouteRecordInfo<'/admin/menu', '/admin/menu', Record<never, never>, Record<never, never>>,
    '/admin/reservations': RouteRecordInfo<'/admin/reservations', '/admin/reservations', Record<never, never>, Record<never, never>>,
    '/auth': RouteRecordInfo<'/auth', '/auth', Record<never, never>, Record<never, never>>,
    '/booking/confirm': RouteRecordInfo<'/booking/confirm', '/booking/confirm', Record<never, never>, Record<never, never>>,
    '/booking/environment': RouteRecordInfo<'/booking/environment', '/booking/environment', Record<never, never>, Record<never, never>>,
    '/booking/seats': RouteRecordInfo<'/booking/seats', '/booking/seats', Record<never, never>, Record<never, never>>,
    '/client/dashboard': RouteRecordInfo<'/client/dashboard', '/client/dashboard', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/menu/[tableId]': RouteRecordInfo<'/menu/[tableId]', '/menu/:tableId', { tableId: ParamValue<true> }, { tableId: ParamValue<false> }>,
    '/staff/dashboard': RouteRecordInfo<'/staff/dashboard', '/staff/dashboard', Record<never, never>, Record<never, never>>,
    '/venue/[id]': RouteRecordInfo<'/venue/[id]', '/venue/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/admin/floor-plan.vue': {
      routes: '/admin/floor-plan'
      views: never
    }
    'src/pages/admin/menu.vue': {
      routes: '/admin/menu'
      views: never
    }
    'src/pages/admin/reservations.vue': {
      routes: '/admin/reservations'
      views: never
    }
    'src/pages/auth.vue': {
      routes: '/auth'
      views: never
    }
    'src/pages/booking/confirm.vue': {
      routes: '/booking/confirm'
      views: never
    }
    'src/pages/booking/environment.vue': {
      routes: '/booking/environment'
      views: never
    }
    'src/pages/booking/seats.vue': {
      routes: '/booking/seats'
      views: never
    }
    'src/pages/client/dashboard.vue': {
      routes: '/client/dashboard'
      views: never
    }
    'src/pages/home.vue': {
      routes: '/home'
      views: never
    }
    'src/pages/menu/[tableId].vue': {
      routes: '/menu/[tableId]'
      views: never
    }
    'src/pages/staff/dashboard.vue': {
      routes: '/staff/dashboard'
      views: never
    }
    'src/pages/venue/[id].vue': {
      routes: '/venue/[id]'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
